project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - site-assets/

lang: en
author-meta: "Joshua Kunst"

website:
  title: "Visual Data Lab"
  site-url: "https://jkunst.com/visual-data-lab/"
  open-graph: true
  twitter-card: true
  google-analytics: "G-ECZ9XLT78C"
  search: false
  navbar:
    title: "jk"
    pinned: true
    right:
      - text: Blog ↗
        href: "https://jkunst.com/blog/"
      - text: Visual Data Lab
        href: index.qmd
      - text: GitHub ↗
        href: "https://github.com/jbkunst/visual-data-lab"

format:
  html:
    theme: cosmo
    css: site-assets/catalog.css
    canonical-url: true
    include-in-header:
      text: |
        <meta name="google-site-verification" content="pLmyRYfU13GaMc8sk2zMHqhTE6r4PvcAJ5C4bK5VW9E">
    toc: false
    anchor-sections: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto
